### ISSUE TITLE
Kopieren von Artikeln mit Subcolumns führt zu einem Fehler (Contao 2.11.12)

### ISSUE THREAD

**Issue by MacKP** [felixpfeiffer/Contao-Subcolumns#19]
Hallo Felix,
es ist mal wieder so weit _G_
Weiß gar nicht ob du da noch was machen willst, bei der Contao Version. Aber ich schreibs dir trotzdem mal.
Fehlermeldung beim Kopieren von Artikeln (Über das schicke grüne +):

'

Warning: sort() expects parameter 1 to be array, null given in â€¦/system/modules/subcolumns/tl_subcolumnsCallback.php on line 155
#0 [internal function]: __error(2, 'sort() expects ...', '/homepages/44/d...', 155, Array)
#1 â€¦/system/modules/subcolumns/tl_subcolumnsCallback.php(155): sort(NULL)
#2 â€¦/system/modules/subcolumns/tl_subcolumnsCallback.php(89): tl_subcolumnsCallback->copyCheck(801)
#3 â€¦/system/drivers/DC_Table.php(884): tl_subcolumnsCallback->articleCheck(801, Object(DC_Table))
#4 â€¦/system/modules/backend/Backend.php(287): DC_Table->copy()
#5 â€¦/contao/main.php(120): Backend->getBackendModule('article')
#6 â€¦/contao/main.php(230): Main->run()
#7 {main}

'

Viele Grüße

**Comment by MrTool** [comment]
Hallo Felix,

Ich hab das problem leider auch unter Contao 3.4.4 wird das noch gefixt oder ist das projekt generell tot?
